# Rubocop is so whiny. Tweak later to keep style consistent with original gem.

EmptyLinesAroundAttributeAccessor:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false
